@startuml
start
:用户查看活动详情;
:点击报名;
if (是否登录?) then (是)
  :查询活动信息;
  if (是否重复报名?) then (否)
    if (报名人数是否小于限制人数?) then (是)
      :保存报名记录;
      :活动报名人数加一;
      :返回报名成功;
    else (否)
      :提示名额已满;
    endif
  else (是)
    :提示已报名;
  endif
else (否)
  :跳转登录页;
endif
stop
@enduml