@startuml
start
:用户进入订单确认页面;
:填写收货信息;
:提交订单;
if (用户是否登录?) then (是)
  :查询商品信息;
  if (商品是否上架?) then (是)
    if (库存是否充足?) then (是)
      :生成订单编号;
      :保存订单主信息;
      :保存订单明细;
      :扣减商品库存;
      :更新商品销量;
      :返回下单成功;
    else (否)
      :提示库存不足;
    endif
  else (否)
    :提示商品已下架;
  endif
else (否)
  :跳转登录页面;
endif
stop
@enduml